### ISSUE TITLE
Port to last version of the `decompress` library

### ISSUE THREAD

**Issue by rlepigre** [rlepigre/ocaml-imagelib#18]
see https://github.com/ocaml/opam-repository/pull/12313.

**Comment by cfcs** [comment]
This will require an explicit bound on either `decompress <= 0.7.0` **or** (preferably) `decompress >= 0.8.0` to prevent situations where we try to compile against the wrong version of `decompress`.

1) @rlpigre what do you think about including an opam file in the repository?
This would allow easier linting and CI of `imagelib` while developing new patches.

2) I propose adding an `imagelib.opam` to do this, and ideally also a `imagelib-unix.opam` package at some point with the Unix-specific things (right now I believe `imagelib` stopped compiling on mirage again due to the Unix dependency I introduced when fixing the shell injection issue).

**Comment by rlepigre** [comment]
@cfcs OK, I'm fine with that.

**Comment by vbgl** [comment]
May this issue be fixed? It would be nice to be able to use “imagelib” with latest “decompress”.

It seems that there is a couple of pull requests that are ready to be merged. Thanks.

**Comment by cfcs** [comment]
I think #23 is ready to be merged, and then we can address @rymdhund's comments in a separate PR.
The reason for not updating that PR is that I have a lot of branches based on #23 that would be tricky to rebase (GIF support, test suite written with @olleolleolle, image scaling, ...).

**Comment by rlepigre** [comment]
@cfcs feel free to merge #23, that looks good to me.
