### ISSUE TITLE
Seems something is broken with last version of decompress

### ISSUE THREAD

**Issue by rlepigre** [rlepigre/ocaml-imagelib#21]
If I try to compile a file `test.ml` containing
```ocaml
let _ = ImageLib.openfile
```
the following, using the command
```bash
ocamlfind ocamlopt -package imagelib -linkpkg -o test test.ml
```
I get the following error.
```bash
File "test.ml", line 1:
Error: No implementations provided for the following modules:
         Checkseum referenced from /home/rodolphe/.opam/4.05.0/lib/decompress/impl/decompress_impl.cmxa(Decompress_impl__Decompress_safe),
           /home/rodolphe/.opam/4.05.0/lib/decompress/impl/decompress_impl.cmxa(Decompress_impl)
         ImageChannels referenced from /home/rodolphe/.opam/4.05.0/lib/imagelib/imagelib.cmxa(ImagePNG)
```

**Comment by zshipko** [comment]
This is actually the expected behavior right now: https://github.com/mirage/decompress#checkseum--optint-linking-with-decompress but I know people are working on simplifying this.

In this case, to make your example work you would need to run:

```
ocamlfind ocamlopt -package checkseum.c -package imagelib -linkpkg -o test test.ml
```

However, I think `ImageChannels` also needs to be added to `imagelib.mllib` to get it to compile successfully.

**Comment by rlepigre** [comment]
OK, I see. Thanks!

**Comment by cfcs** [comment]
I've fixed that in this branch, which still needs some work. :) 
https://github.com/cfcs/ocaml-imagelib/tree/mirage_compat
